### ISSUE TITLE
运行yolo.py，取消其中的tensorboard注释，从而可视化模型

### ISSUE THREAD

**Issue by fanzhen12** [liudakai2/UnsupDIS-pytorch#12]
为了可视化模型，我将yolo.py文件中的这一段注释去掉：
![image](https://user-images.githubusercontent.com/40566781/182602838-5b935e50-5c2e-4636-be6f-d11037f3e01a.png)
取消后代码如下：
![image](https://user-images.githubusercontent.com/40566781/182605006-f44733bc-acc9-48b6-a724-f3f00c9d6dea.png)
然后我运行yolo.py代码，结果如下：
![image](https://user-images.githubusercontent.com/40566781/182605149-3bff88eb-4d32-42f1-bdd9-2bd0b7716337.png)
请问这是为什么？是不是我把模型的输入搞错了，即这一行：
![image](https://user-images.githubusercontent.com/40566781/182605366-98252e2f-f05f-4d92-947c-a3162c688df0.png)
是这个原因吗？
报错之后，我将生成的tensorboard日志文件用终端命令打开，结果就无内容显示，出现错误
![image](https://user-images.githubusercontent.com/40566781/182605812-2dda7646-27cf-4d9d-80de-ec0f2868214c.png)

**Comment by liudakai2** [comment]
(1,8,128,128)
