### ISSUE TITLE
可运行的模型打印代码

### ISSUE THREAD

**Issue by fanzhen12** [liudakai2/UnsupDIS-pytorch#13]
您好，请问您能否提供一段可运行的打印align阶段与fuse阶段模型的代码，在运行yolo.py文件时，我想要打印align模型，所以运行如下代码：
![image](https://user-images.githubusercontent.com/40566781/182856576-2b733c78-1398-4f6c-a042-4af043a8a78b.png)
但出现如下错误：
![image](https://user-images.githubusercontent.com/40566781/182856676-f414d30a-fee0-4fcd-815f-65f68e63bc90.png)
即提示我“给定组=1，大小为 [64, 12, 3, 3] 的权重，预期输入 [2, 24, 64, 64] 有 12 个通道，但有 24 个通道“，请问能否提供一个可以运行的简短的打印align模型和fuse模型的代码，感谢

**Comment by liudakai2** [comment]
你可以在你之前问过的一个一模一样的问题中找到你想要的答案
https://github.com/liudakai2/UnsupDIS-pytorch/issues/3#issue-1249268702

**Comment by nqrbjwd** [comment]
Yes, I have the same question with him/her. It's true that the input shape of the model you mentioned is (8, 128, 128), 
 
![image](https://user-images.githubusercontent.com/110882119/183564644-43f3aa39-e79c-45ae-8159-b75fec246804.png)

but this error will always occur when printing the specific information of the model in the summary. 
 
![image](https://user-images.githubusercontent.com/110882119/183564674-577b2e7e-5146-4cd7-b24b-55209087bdb9.png)

Therefore, shall you publish a minimum runnable model-printing code, both fuse and align.

**Comment by nqrbjwd** [comment]
Thank you very much. It's very helpful to us ╰(*°▽°*)╯
