### ISSUE TITLE
GPU使用率問題

### ISSUE THREAD

**Issue by Scott-che** [liudakai2/UnsupDIS-pytorch#14]
你好，想請問在執行train.py時，為何在工作管理員的CPU使用率好高，但GPU使用率偏低，似乎沒用到cuda；不過我並沒有更改你的code，而是按照github上的步驟執行

**Comment by liudakai2** [comment]
因为模型不大，GPU使用率偏低是正常的；GPU显存和使用率一直为0才不正常。
