### ISSUE TITLE
测试集在eval中的结果与train中的差距较大

### ISSUE THREAD

**Issue by FXMEIa** [liudakai2/UnsupDIS-pytorch#15]
您好，请问修改了网络结构，在训练过程中train.py的代码也需要修改嘛？我使用修改后的代码得到的模型测试,与训练过程中测试集的PSNR,SSIM差异较大

**Comment by tgjjj** [comment]
你好，一般来说只是修改网络结构是不需要修改训练代码的。
但仅凭现在的问题描述我们无法判断问题所在，你能提供更详细的代码和日志吗，包括：
-训练和测试使用的命令
-对应的训练和测试的PSNR结果
-如果可以的话，具体怎么修改的网络结构

**Comment by FXMEIa** [comment]
您好，这个问题已经解决了。我还想问一下，您使用COCO数据合成训练数据时，随机扰动是在【-32，32】之间嘛？

**Comment by liudakai2** [comment]
> 您好，这个问题已经解决了。我还想问一下，您使用COCO数据合成训练数据时，随机扰动是在【-32，32】之间嘛？

你好，我们用的是原repo提供的合成数据，没有自己生成、
按照原作的说法，是用这个脚本生成的
https://github.com/nie-lang/UnsupervisedDeepImageStitching/blob/main/ImageAlignment/synthetic_dataset.py
