### ISSUE TITLE
RuntimeError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnSgetrf( handle, m, n, dA, ldda, static_cast<float*>(dataPtr.get()), ipiv, info)`

### ISSUE THREAD

**Issue by xqtr123** [liudakai2/UnsupDIS-pytorch#16]
![image](https://user-images.githubusercontent.com/82517438/190054365-6887eedf-845b-4b68-8dcc-ea73461fde68.png)
运行yolo.py和train.py时都会出现这样的错误，把设备从gpu改为cpu时可以正常运行，请问是什么原因？

**Comment by tgjjj** [comment]
我们没有遇到过这个问题，但可能是PyTorch版本导致的，我们使用的是PyTorch 1.10.1。

**Comment by liudakai2** [comment]
你好，可能需要升级nvidia driver和cuda版本
https://github.com/pytorch/pytorch/issues/70122#issuecomment-1014246828
