### ISSUE TITLE
你好，这一行报错，请问怎么解决呢

### ISSUE THREAD

**Issue by liu-ai-z** [liudakai2/UnsupDIS-pytorch#17]
H_8el = torch.linalg.solve(A_mat.float(), b_mat.float()).type(dtype).squeeze(-1)  # [bs,8]
AttributeError: module 'torch.linalg' has no attribute 'solve'

**Comment by liudakai2** [comment]
你好，`torch.linalg.solve`模块在pytorch 1.8.0及之后版本支持，请检查torch版本

**Comment by liu-ai-z** [comment]
训练过程中，再COCO和UDIS-D训练数据，损失、PSRN、SSIM没变化这是正常的吗
