### ISSUE TITLE
LOSS

### ISSUE THREAD

**Issue by lxc5720** [liudakai2/UnsupDIS-pytorch#23]
大佬好，如果我想训练原来的网络结构，是否需要把下图中的1换成2呢，此外我发现在第一个对齐阶段，原论文跟大佬你们的，只是用到了L1损失，不知道是否可以加入SSIM损失呢，亦或者MS-SSIM损失呢

![image](https://user-images.githubusercontent.com/68238668/201286384-3c303c5e-4be4-4766-85b9-747c42eb9f06.png)

**Comment by tgjjj** [comment]
你好，不需要更改代码，两种模型调用的分别是HEstimator和HEstimatorOrigin类，这个函数是不一样的，只要在调用的时候将模型的yaml文件指定为origin后缀的就行，可以参考main.sh里第六行的写法。
关于损失，这个我们没有探索过，不过这个想法可以尝试。

**Comment by lxc5720** [comment]
好的，感谢您的回答，就在刚刚我尝试了L1+SSIM 作为损失函数，但是在测试时发生了错误，不明白是什么原因导致错误产生的，具体错误如下：

希望您能指点一下下，万分感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liudakai2/UnsupDIS-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 下午3:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liudakai2/UnsupDIS-pytorch] LOSS (Issue #23)





 
你好，不需要更改代码，两种模型调用的分别是HEstimator和HEstimatorOrigin类，这个函数是不一样的，只要在调用的时候将模型的yaml文件指定为origin后缀的就行，可以参考main.sh里第六行的写法。
 关于损失，这个我们没有探索过，不过这个想法可以尝试。

**Comment by tgjjj** [comment]
我这边看不到你的错误内容，不知道什么情况
![图片](https://user-images.githubusercontent.com/35397867/201860829-c91dd951-b5ae-407f-9075-66a6d8b5b439.png)

**Comment by lxc5720** [comment]
![image](https://user-images.githubusercontent.com/68238668/201861141-edde2d84-d141-4648-91de-dc5a506f3270.png)
这是出现的错误，我去查看了temp文件夹，文件夹的内容如下：
![image](https://user-images.githubusercontent.com/68238668/201861461-ecf03ceb-05b4-45d6-97d3-ee1c7ba3385c.png)

**Comment by tgjjj** [comment]
这个是由于Warped Images里出现了全黑（整个Tensor都是0）的情况导致的，从图里看的话应该是00、06和07这三张的问题。
可以先检查一下网络输出的Vertices Offset的值是否正常。
也可以参考另一个Issue
https://github.com/liudakai2/UnsupDIS-pytorch/issues/22
