### ISSUE TITLE
请问在最后一层根据偏移量求解H之后，为什么还要变成M_inv×H×M？

### ISSUE THREAD

**Issue by Colin-Jing** [liudakai2/UnsupDIS-pytorch#24]
![image](https://user-images.githubusercontent.com/60170481/204080526-5daf0044-fbf5-4777-9d1c-181290a06a07.png)

一开始我以为是为了匹配特征层大小，但是自己算出来发现不是这么回事，请问这里的相似矩阵的用处是什么呢？

**Comment by liudakai2** [comment]
这里只是保持透视变换矩阵的形状为[bs, 3, 3]，跟特征层尺寸没关系
