### ISSUE TITLE
关于模型问题

### ISSUE THREAD

**Issue by baolongqishi** [liudakai2/UnsupDIS-pytorch#25]
您好，请问一下models里的这个模型可以共享一下吗？是否可以用models文件夹下的其他align_xx模型代替呢？
![image](https://user-images.githubusercontent.com/89435058/204704206-452bd733-9d42-47bc-9bc6-8c289e604f41.png)

**Comment by liudakai2** [comment]
你好，这个文件名没意义的，你可以选择models/下面不同的配置文件

**Comment by baolongqishi** [comment]
谢谢老师，非常感谢您能回复！



---原始邮件---
发件人: "Liu ***@***.***&gt;
发送时间: 2022年11月30日(周三) 中午12:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liudakai2/UnsupDIS-pytorch] 关于模型问题 (Issue #25)




 
你好，这个文件名没意义的，你可以选择models/下面不同的配置文件
