### ISSUE TITLE
请问pretrained model的align阶段训练了多少个epoch？

### ISSUE THREAD

**Issue by yayoyo66** [liudakai2/UnsupDIS-pytorch#29]
我按照Training, Testing, and Inference里的说明训练了align模型，但训练模型的测试结果和coco_align_yolo.pt的结果差距非常大， 我注意到Training, Testing, and Inference里warpcoco的epoch是50 epochs，udis finetuning是30 epochs，而原论文中写的是Stitched MS-COCO 训练了150 epochs，真实数据训练了 50 epochs。我想知道预训练模型的训练epoch以及其他训练参数是和Training, Testing, and Inference里写的是一致的吗，还是不同的？

**Comment by tgjjj** [comment]
我们的预训练模型是按照main.sh里的参数训练的，Warped-COCO 150 epoch，UDIS-D 50 epoch。
其他参数也尽量参考main.sh，readme里是旧版的训练参数。

**Comment by yayoyo66** [comment]
> 我们的预训练模型是按照main.sh里的参数训练的，Warped-COCO 150 epoch，UDIS-D 50 epoch。 其他参数也尽量参考main.sh，readme里是旧版的训练参数。

好的，感谢解答！
