### ISSUE TITLE
the model input

### ISSUE THREAD

**Issue by fanzhen12** [liudakai2/UnsupDIS-pytorch#3]
我想要观察一个网络，所以采取如下代码(以另外的一个网络模型为例)：
(I want to observe a network, so I adopt the following code (take another network model as an example):)
![image](https://user-images.githubusercontent.com/40566781/170448807-35f65ead-9d08-4b91-8d1d-422a445e5783.png)
结果如图所示(结果分为两部分，如代码所示，一部分是网络模型，一部分显示出具体每一层的参数)：
The results are shown in the figure (the results are divided into two parts, as shown in the code. One part is the network model and the other part shows the parameters of each layer):
![image](https://user-images.githubusercontent.com/40566781/170448908-923dfee4-4fa3-4c1b-867d-3baaf1e2d7a0.png)
![image](https://user-images.githubusercontent.com/40566781/170448992-bf36e0bb-59fc-4bcf-8461-416e0e59101d.png)

同样地，我想要观察这个网络，所以采取如下代码(所有的包都已被引入)：
Similarly, I want to observe this network, so I take the following code (all packages have been introduced):
![image](https://user-images.githubusercontent.com/40566781/170449061-7c8d248f-45dc-4a79-8a67-6b91dc8bf6a9.png)
结果如图所示(结果分为两部分，如代码所示，一部分是网络模型，一部分显示出具体每一层的参数)：
The results are shown in the figure (the results are divided into two parts, as shown in the code. One part is the network model and the other part shows the parameters of each layer):
网络模型如下所示(由于太长，之截取一部分，网络模型正常显示)
The network model is as follows (because it is too long, some of it is intercepted, and the network model is displayed normally)
![image](https://user-images.githubusercontent.com/40566781/170449700-a630eb36-709d-4b83-bcd5-a0b0d4e4968e.png)
但是，在运行summary函数时，出现以下错误，
However, when running the summary function, the following error occurs:,
![image](https://user-images.githubusercontent.com/40566781/170449935-32f95c94-6a34-495a-afab-446887b618c6.png)
错误在于 summary(model,(8,128,128)) 这一行，在summary函数中：
The error lies in the line of summary (model, (8128128)). In the summary function:
![image](https://user-images.githubusercontent.com/40566781/170450205-d10c82b2-d4a3-457a-bdde-9899613cf532.png)
我不知道网络的输入是什么，因此总是无法通过此段代码打印出每一层的参数，我想请问一下，网络的输入形状是什么？
I don't know what the input of the network is, so I can't print out the parameters of each layer through this code. So I have a question: What is the input shape of the network?

**Comment by liudakai2** [comment]
输入tensor的shape是[8,128,128]，请传入mode_align关键字参数

**Comment by liudakai2** [comment]
如果summary不提供kwargs接口，你也可以依次在yolo.py中修改mode_align参数的默认值，分别打印align和fuse两个不同阶段的网络

**Comment by fanzhen12** [comment]
请允许我像您请教两个问题：
问题一：
![image](https://user-images.githubusercontent.com/40566781/170453426-8f3eda1f-b8bb-496a-a777-8ee10b826a76.png)
经过修改，我使得mode_align=False变成了mode_align=True，同时经过将shape修改为: [8,128,128]，代码段变为：
![image](https://user-images.githubusercontent.com/40566781/170453780-2bb6ca29-e606-4575-aa9e-9b9d7683c724.png)
出现了以下一个错误：
![image](https://user-images.githubusercontent.com/40566781/170453864-30b05e3e-dea2-49de-a0d7-8aec18732d00.png)
也即是TypeError: Value after * must be an iterable, not int，请问这是为什么？
##########################################################################################
问题二：
请问，还有哪里我没有改对，另外，请问 model_align 是一个已经默认的参数，所以应该无需再传入，我试了一下，如果传入，代码段变为
![image](https://user-images.githubusercontent.com/40566781/170454371-43f24c72-4aa3-4be6-8148-e5e011cb83d7.png)
是我model_align 传入的位置不对吗?

**Comment by liudakai2** [comment]
1. 或许你可以试试tuple类型的(8,128,128)而非list类型
2. model_align是调用model实例的forward函数传入的参数，不是构造函数中的参数

**Comment by fanzhen12** [comment]
在将[8,128,128]换成(8,128,128)后，我看到了希望，错误变成了
![image](https://user-images.githubusercontent.com/40566781/170456047-6c59832c-00b7-433b-bbd6-1a65d8c2607f.png)
翻译过来也即：
![image](https://user-images.githubusercontent.com/40566781/170456094-1d0655a4-3c36-4e5d-b35d-84014d1f4d81.png)
我觉得应该快要成功了，请问，这是什么情况？

**Comment by liudakai2** [comment]
model = Model(opt.cfg, ch=3).cuda()

**Comment by fanzhen12** [comment]
![image](https://user-images.githubusercontent.com/40566781/170467593-388f49e1-2ece-4931-ac90-b923781702c4.png)
我又遇到了这个问题，我正在尝试解决它，如果你有什么建议，请告诉我好吗，如果我解决了，我会告诉你

**Comment by fanzhen12** [comment]
![image](https://user-images.githubusercontent.com/40566781/170471244-d9cec52f-86a9-4762-a234-ef0c40aae396.png)
![image](https://user-images.githubusercontent.com/40566781/170471275-2370a3f9-a253-4f33-9ece-254790137f2c.png)
![image](https://user-images.githubusercontent.com/40566781/170471295-a3d6d9b5-f2c2-47cc-8e01-1a0a64709d55.png)
![image](https://user-images.githubusercontent.com/40566781/170471326-7dd2daa1-222e-4ec2-823c-6412da882e92.png)
![image](https://user-images.githubusercontent.com/40566781/170471358-76a5e1e5-fe59-4c19-876e-5e270eb8544a.png)
![image](https://user-images.githubusercontent.com/40566781/170471384-9d89fa4a-5add-48c0-8ba0-a03e46f4577a.png)
![image](https://user-images.githubusercontent.com/40566781/170471416-e7e0b36b-d9f1-4299-853a-17b3686ab2e7.png)
![image](https://user-images.githubusercontent.com/40566781/170471449-203c2368-21a7-4fc4-8afc-41f94afdd9af.png)
![image](https://user-images.githubusercontent.com/40566781/170471472-39658e66-ae27-4aa7-a74c-c2660f00b39f.png)
![image](https://user-images.githubusercontent.com/40566781/170471491-fb7f4ef4-00a5-4ae3-ad22-a5fc5f7bb360.png)
![image](https://user-images.githubusercontent.com/40566781/170471534-0ad247f8-1482-414f-adc3-34ab841e0b66.png)
![image](https://user-images.githubusercontent.com/40566781/170471558-6616a1b5-b0a9-452e-b633-8ba69104f97e.png)
我似乎已经把模型进行了可视化，但正如你所见，有一个keyError错误，我不确定它是否可以忽略。

**Comment by fanzhen12** [comment]
如果我已经完成了align阶段网络的打印，请问，对于fuse阶段网络的打印，我是不是应该把yolo.py文件中的model_align=True改为model_align=False，以及代码段改为：
![image](https://user-images.githubusercontent.com/40566781/170472986-0135b29f-134e-46c0-a6c6-5b7c799b58e1.png)


还请问，fuse阶段的输入tensor形状是什么

**Comment by liudakai2** [comment]
我保持了两个阶段的输入tensor形状的一致性，建议多看看代码
