### ISSUE TITLE
STN及stitching domain transform差異

### ISSUE THREAD

**Issue by che1007** [liudakai2/UnsupDIS-pytorch#30]
你好，想請問在stitching.py裡，有STN及stitching domain transform，不太清楚實際的差異。以及想問哪一個才是復現原作者在論文提及的Stitching-Domain Transformer Layer

**Comment by liudakai2** [comment]
两者都是复现的原论文，STN是对feature tensor进行操作，Stitching_Domain_STN是对raw RGB image进行操作
