### ISSUE TITLE
用该方法对自己拍摄的数据集进行拼图,拼接部分会有重影

### ISSUE THREAD

**Issue by DiKu-nn** [liudakai2/UnsupDIS-pytorch#34]
用该方法对自己拍摄的数据集进行拼图,拼接部分会有重影.这是否说明该方法在拼接的时候需要保证两张图片中有完全一样的地方吗?因为我发现USID-D的数据集有点像从大图中截取不同区域制作而成的,所以拼接之后不存在重影吗?

**Comment by DiKu-nn** [comment]
请问您在使用这个方法中会存在重影现象吗?

**Comment by liudakai2** [comment]
此方法对两张图重叠区域要求比较高，不过重建阶段可以缓解重影的问题，但无法彻底解决
