### ISSUE TITLE
训练variant的fuse模型时报错ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by yayoyo66** [liudakai2/UnsupDIS-pytorch#35]
我尝试训练variant的fuse模型，align模型已经训练成果，在训练fuse模型时设置使用了 models/fuse_variant.yaml 和
data/hyp.fuse.scratch.yaml（没找到这个的variant设置），weights为models/yolo/yolov5m.pt
在语句`optimizer = optim.Adam(pg2, lr=float(hyp['lr0']), betas=(hyp['momentum'], 0.999))  # adjust beta1 to momentum`处报错：

ValueError: optimizer got an empty parameter list

我检查了一下是因为pg2为空数组，且模型的bias全为False，我想知道variant的fuse模型是还未完成吗，还是我的使用方式不对？

**Comment by liudakai2** [comment]
你好，我们没有训练过variant的fuse模型，您或许可以通过修改optimizer的初始化来开始训练
