### ISSUE TITLE
inference_align.py的一些问题

### ISSUE THREAD

**Issue by LiYQi** [liudakai2/UnsupDIS-pytorch#37]
您好，我发现在训练时传入模型中的图片次序为img2（input2），mask2，img1（input1），mask1，但是在inference_align.py中的parse_source函数生成的dataloader的次序为msk2, img2（input2）, msk1, img1（input1），所以，我想请问一下parse_source是不是需要更改一下？

**Comment by liudakai2** [comment]
不需要。将img和msk在channel维度stack到一起传入`img_numpy2torch`函数，会将img和msk的顺序自动复原回来。
