### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Onlydrink** [liudakai2/UnsupDIS-pytorch#40]
为什么本地跑可以，在云服务器上，会出现opencv读不到图片的错误，在根目录下也存在WarpedCOCO数据集的文件夹，也有数据集的软连接。

**Comment by liudakai2** [comment]
建议再检查下路径

**Comment by QinAolong** [comment]
> 



> 为什么本地跑可以，在云服务器上，会出现opencv读不到图片的错误，在根目录下也存在WarpedCOCO数据集的文件夹，也有数据集的软连接。

你好 可以请教一下你在本地跑的时候 数据集怎么软链接的嘛

**Comment by Onlydrink** [comment]
> > 
> 
> > 为什么本地跑可以，在云服务器上，会出现opencv读不到图片的错误，在根目录下也存在WarpedCOCO数据集的文件夹，也有数据集的软连接。
> 
> 你好 可以请教一下你在本地跑的时候 数据集怎么软链接的嘛

你好 因为本地是windows系统，可以直接跑通，所以没用软链接，

**Comment by QinAolong** [comment]
> > > 
> > 
> > 
> > > 为什么本地跑可以，在云服务器上，会出现opencv读不到图片的错误，在根目录下也存在WarpedCOCO数据集的文件夹，也有数据集的软连接。
> > 
> > 
> > 你好 可以请教一下你在本地跑的时候 数据集怎么软链接的嘛
> 
> 你好 因为本地是windows系统，可以直接跑通，所以没用软链接，
没用软链接可以直接跑通嘛 需要修改代码嘛 因为我直接跑会遇到问题 就是找不到我的图片

**Comment by Onlydrink** [comment]
> > > > 
> > > 
> > > 
> > > > 为什么本地跑可以，在云服务器上，会出现opencv读不到图片的错误，在根目录下也存在WarpedCOCO数据集的文件夹，也有数据集的软连接。
> > > 
> > > 
> > > 你好 可以请教一下你在本地跑的时候 数据集怎么软链接的嘛
> > 
> > 
> > 你好 因为本地是windows系统，可以直接跑通，所以没用软链接，
> > 没用软链接可以直接跑通嘛 需要修改代码嘛 因为我直接跑会遇到问题 就是找不到我的图片


这个是作者在另外一个问题下的回答，你可以试一下。你要在根目录下有WarpedCOCO这个数据集文件夹。我就是加了个文件夹，然后下载了相应数据集就可以跑通了。

作者的原回答：
看起来是OpenCV读取图像失败的问题，请确认数据集路径是否正确。
在main.sh所在的目录下应该存在WarpedCOCO这个数据集文件夹，如果没有的话请参考下面的命令建立软链接。

**Comment by QinAolong** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > 为什么本地跑可以，在云服务器上，会出现opencv读不到图片的错误，在根目录下也存在WarpedCOCO数据集的文件夹，也有数据集的软连接。
> > > > 
> > > > 
> > > > 你好 可以请教一下你在本地跑的时候 数据集怎么软链接的嘛
> > > 
> > > 
> > > 你好 因为本地是windows系统，可以直接跑通，所以没用软链接，
> > > 没用软链接可以直接跑通嘛 需要修改代码嘛 因为我直接跑会遇到问题 就是找不到我的图片
> 
> 这个是作者在另外一个问题下的回答，你可以试一下。你要在根目录下有WarpedCOCO这个数据集文件夹。我就是加了个文件夹，然后下载了相应数据集就可以跑通了。
> 
> 作者的原回答： 看起来是OpenCV读取图像失败的问题，请确认数据集路径是否正确。 在main.sh所在的目录下应该存在WarpedCOCO这个数据集文件夹，如果没有的话请参考下面的命令建立软链接。

噢噢 那就是直接在根目录把WarpedCOCO这个数据集放上就行吧 我试试

**Comment by QinAolong** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > 为什么本地跑可以，在云服务器上，会出现opencv读不到图片的错误，在根目录下也存在WarpedCOCO数据集的文件夹，也有数据集的软连接。
> > > > 
> > > > 
> > > > 你好 可以请教一下你在本地跑的时候 数据集怎么软链接的嘛
> > > 
> > > 
> > > 你好 因为本地是windows系统，可以直接跑通，所以没用软链接，
> > > 没用软链接可以直接跑通嘛 需要修改代码嘛 因为我直接跑会遇到问题 就是找不到我的图片
> 
> 这个是作者在另外一个问题下的回答，你可以试一下。你要在根目录下有WarpedCOCO这个数据集文件夹。我就是加了个文件夹，然后下载了相应数据集就可以跑通了。
> 
> 作者的原回答： 看起来是OpenCV读取图像失败的问题，请确认数据集路径是否正确。 在main.sh所在的目录下应该存在WarpedCOCO这个数据集文件夹，如果没有的话请参考下面的命令建立软链接。

![image](https://github.com/liudakai2/UnsupDIS-pytorch/assets/96297179/6bba2135-a7a1-40c2-ac34-8fc4e7fcc8显示没有权限
