### ISSUE TITLE
训练中的问题

### ISSUE THREAD

**Issue by BJTU-LF** [liudakai2/UnsupDIS-pytorch#41]
老师您好，我下载了数据集放在指定位置后训练报错了，请问您知道如何修改吗，谢谢老师
![1685178917323](https://github.com/liudakai2/UnsupDIS-pytorch/assets/134774189/c7769b0e-d2ec-4eeb-b6cc-44fc1212f5c8)

**Comment by liudakai2** [comment]
建议再检查下运行命令，PyCharm是需要额外配置的
