### ISSUE TITLE
'Model' object has no attribute 'hyp'

### ISSUE THREAD

**Issue by onlyNata** [liudakai2/UnsupDIS-pytorch#7]
file:  utils/loss.py  line 15 
  self.hyp=model.hyp

**Comment by tgjjj** [comment]
Thanks for your report. If you encountered this when using the "test.py" script, it could possibly be solved by adding the following line in models/experimental.py line 121.
setattr(model[-1], 'hyp', ckpt['model'].hyp)
like this,
![图片](https://user-images.githubusercontent.com/35397867/175760889-6b6d3da0-5450-41c4-bc9f-04c0750841fc.png)
We will fix this in the next commit.

**Comment by liudakai2** [comment]
Bug fixed.
